name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Make build directory
        run: mkdir ${{github.workspace}}/Build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/Build

      - name: Build Project
        run: cmake --build ${{github.workspace}}/Build --config ${{env.BUILD_TYPE}}
