name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Get Linux dependencies
        run: |
          sudo apt-get update
          sudo apt install g++ libasoudn2-dev libjack-jackd2-dev ladspa-sdk libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get submodules
        run: git submodule update --init --recursive

      - name: Make build directory
        run: mkdir ${{github.workspace}}/Build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/Build

      - name: Build Project
        run: cmake --build ${{github.workspace}}/Build --config ${{env.BUILD_TYPE}}
